@startuml
start
:Открытие меню;
:Выбор позиции;
:Настройка количества,\nдобавок и модификаторов;
:Добавление позиции в корзину;
:Переход к оформлению заказа;
:Проверка авторизации;
if (Пользователь авторизован?) then (да)
  :Ввод комментария,\nтипа заказа и времени самовывоза;
  :Расчет стоимости,\nКБЖУ и скидки;
  :Отправка заказа через API;
  if (Заказ создан?) then (да)
    :Показ подтверждения\nи статуса заказа;
  else (нет)
    :Показ ошибки оформления;
  endif
else (нет)
  :Переход к авторизации;
endif
stop
@enduml
