@startuml
start
:Авторизация сотрудника;
:Открытие очереди заказов;
:Получение актуального списка заказов;
:Выбор заказа;
:Просмотр состава,\nкомментария и времени подачи;
if (Нужна техкарта?) then (да)
  :Открытие технологической карты;
endif
:Приготовление позиции;
:Отметка готовности позиции;
if (Все позиции готовы?) then (да)
  :Изменение статуса заказа\nна готовый;
else (нет)
  :Ожидание готовности\nоставшихся позиций;
endif
:Обновление статуса в API;
stop
@enduml
