@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
skinparam ArrowColor Black
skinparam linetype polyline
skinparam roundcorner 8
skinparam nodesep 55
skinparam ranksep 55
skinparam rectangle {
  BackgroundColor White
  BorderColor Black
  FontColor Black
  FontStyle bold
}

left to right direction

rectangle "Окно \"Технологические\nкарты\"\n19" as TechCards
rectangle "Пользователь" as User
rectangle "Окно \"Персонал и\nаналитические отчеты\"\n37, 38" as ReportsStaff

rectangle "Окно \"Производственная\nочередь заказов\"\n16, 17, 18, 20, 21" as Orders
rectangle "Главное меню" as MainMenu
rectangle "Окно \"Меню и\nкатегории меню\"\n23, 24, 25, 26, 27, 28" as MenuAdmin

rectangle "Окно \"Заготовки и\nакты списания\"\n33, 34" as WriteOffPrep
rectangle "Окно \"Создание\nзаказа\"\n22" as OrderCreate
rectangle "Окно \"Склад и\nстоп-лист\"\n29, 30, 31, 32" as InventoryStop
rectangle "Окно \"Клиенты,\nлояльность и\nистория заказов\"\n35, 36" as ClientsLoyalty

TechCards -[hidden]right-> User
User -[hidden]right-> ReportsStaff
Orders -[hidden]right-> MainMenu
MainMenu -[hidden]right-> MenuAdmin
WriteOffPrep -[hidden]right-> OrderCreate
OrderCreate -[hidden]right-> InventoryStop
InventoryStop -[hidden]right-> ClientsLoyalty
User -[hidden]down-> MainMenu
MainMenu -[hidden]down-> OrderCreate

User --> MainMenu : 15
MainMenu --> TechCards : 19
TechCards --> MainMenu : 39
MainMenu --> ReportsStaff : 37, 38
ReportsStaff --> MainMenu : 39
MainMenu --> Orders : 16
Orders --> MainMenu : 39
MainMenu --> MenuAdmin : 23
MenuAdmin --> MainMenu : 39
MainMenu --> WriteOffPrep : 33, 34
WriteOffPrep --> MainMenu : 39
MainMenu --> OrderCreate : 22
OrderCreate --> MainMenu : 39
MainMenu --> InventoryStop : 29
InventoryStop --> MainMenu : 39
MainMenu --> ClientsLoyalty : 35, 36
ClientsLoyalty --> MainMenu : 39
Orders --> TechCards : 19
InventoryStop --> MenuAdmin : 31, 32
ClientsLoyalty --> ReportsStaff : 38
WriteOffPrep --> InventoryStop : 33, 34

@enduml
