@startuml
start
:Открытие формы авторизации;
:Ввод логина и пароля;
:Отправка учетных данных через API;
:Проверка пользователя и роли;
if (Данные корректны?) then (да)
  :Создание защищенной сессии;
  :Загрузка доступных разделов;
  if (Роль клиента?) then (да)
    :Переход в веб-интерфейс клиента;
  else (нет)
    :Переход в WPF-интерфейс сотрудника;
  endif
else (нет)
  :Показ сообщения об ошибке;
  :Возврат к форме авторизации;
endif
stop
@enduml
