@startuml
start
:Получить технологическую карту позиции;
:Получить список ингредиентов;
:Инициализировать суммы КБЖУ\nи себестоимости;
while (Есть следующий ингредиент?) is (да)
  :Получить массу ингредиента;
  :Получить КБЖУ на 100 г\nи цену единицы массы;
  :Рассчитать вклад ингредиента\nв КБЖУ;
  :Рассчитать вклад ингредиента\nв себестоимость;
  :Добавить значения к итогам;
endwhile (нет)
:Применить коэффициент наценки;
:При оформлении заказа\nприменить скидку клиента;
:Вернуть итоговые КБЖУ,\nсебестоимость и цену;
stop
@enduml
