@startuml
title Алгоритм расчета стоимости и калорийности заказа

left to right direction

skinparam backgroundColor white
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
skinparam ArrowColor black
skinparam rectangle {
  BackgroundColor white
  BorderColor black
  FontColor black
  RoundCorner 10
}

rectangle "Получение\nданных заказа" as A
rectangle "Загрузка блюд,\nнапитков, добавок\nи скидки" as B
rectangle "Обработка\nпозиции заказа" as C
rectangle "Проверка:\nесть добавки?" as D
rectangle "Расчет добавок:\nцена, калории,\nитоговое количество" as E
rectangle "Расчет строки:\nстоимость +\nкалорийность" as F
rectangle "Суммирование\nстрок заказа" as G
rectangle "Проверка:\nесть скидка?" as H
rectangle "Применение\nкоэффициента\nскидки" as I
rectangle "Округление\nTotalPrice и\nTotalCalories" as J
rectangle "Сохранение\nитогов заказа" as K

A --> B
B --> C
C --> D
D --> E : да
E --> F
D --> F : нет
F --> G
G --> H
H --> I : да
I --> J
H --> J : нет
J --> K

@enduml
