@startuml
skinparam shadowing false
skinparam monochrome true

node "Устройство клиента" {
  artifact "Браузер\nGardenNookWeb" as Browser
}

node "Рабочая станция сотрудника" {
  artifact "GardenNookWpf.exe" as Wpf
}

node "Сервер приложения" {
  artifact "GardenNookApi" as Api
  artifact "GardenNookWeb" as Web
}

database "Сервер БД\nMS SQL Server" as Db

Browser --> Web : HTTPS
Web --> Api : HTTPS / JSON
Wpf --> Api : HTTPS / JSON
Api --> Db : SQL / EF Core
@enduml
