// <auto-generated />
using System;
using GardenNookApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenNookApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309154559_AddOrderStatusesStatusId")]
    partial class AddOrderStatusesStatusId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GardenNookApi.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrderCount")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clients__3214EC07C44E7277");

                    b.HasIndex("ClientCategoryId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_Clients_PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ClientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ClientCa__3214EC075DD76994");

                    b.ToTable("ClientCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Discount__3214EC077C9057B9");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaloriesKcal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("CarbsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FatsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Kilojoules")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("MarkupPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PriceRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ProteinsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Dishes__3214EC07F3AB62F1");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DishCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__DishCate__3214EC074FB42ABA");

                    b.ToTable("DishCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DishTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OrderDishItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DishTopp__3214EC0728CBD9E9");

                    b.HasIndex("OrderDishItemId");

                    b.HasIndex("ToppingId");

                    b.ToTable("DishToppings");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaloriesKcal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("CarbsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FatsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Kilojoules")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("MarkupPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PriceRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ProteinsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Drinks__3214EC0711C11292");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DrinkCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__DrinkCat__3214EC071FC1B902");

                    b.ToTable("DrinkCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DrinkTopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OrderDrinkItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("ToppingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__DrinkTop__3214EC079A8C6397");

                    b.HasIndex("OrderDrinkItemId");

                    b.HasIndex("ToppingId");

                    b.ToTable("DrinkToppings");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Stock")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Ingredie__3214EC07E34616FD");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("GardenNookApi.Entities.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Ingredie__3214EC079A4C52A6");

                    b.ToTable("IngredientCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Stock")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inventor__3214EC072D2A73E6");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("GardenNookApi.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<decimal?>("TotalCalories")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Orders__3214EC0762C21CEE");

                    b.HasIndex("ClientId");

                    b.HasIndex("DiscountId");

                    b.HasIndex("OrderTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDishItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DishId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDis__3214EC075A82A4EF");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDishItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDrinkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DrinkId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id")
                        .HasName("PK__OrderDri__3214EC07032F8B5B");

                    b.HasIndex("DrinkId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDrinkItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatuses");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderToppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ToppingId");

                    b.ToTable("OrderToppingItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__OrderTyp__3214EC078DA72059");

                    b.ToTable("OrderTypes");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Preparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("date");

                    b.Property<int?>("SemiFinishedId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StockGrams")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Preparat__3214EC07D64E207C");

                    b.HasIndex("SemiFinishedId");

                    b.ToTable("Preparations");
                });

            modelBuilder.Entity("GardenNookApi.Entities.SemiFinished", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaloriesKcal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("CarbsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FatsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("Kilojoules")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("ProteinsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SemiFini__3214EC075EDA3B4D");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("SemiFinished", (string)null);
                });

            modelBuilder.Entity("GardenNookApi.Entities.SemiFinishedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__SemiFini__3214EC0732760261");

                    b.ToTable("SemiFinishedCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Staff__3214EC07E332FC49");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Login" }, "UQ_Staff_Login")
                        .IsUnique()
                        .HasFilter("[Login] IS NOT NULL");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("GardenNookApi.Entities.StaffRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__StaffRol__3214EC07FFE07C44");

                    b.ToTable("StaffRoles");
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Technica__3214EC07C2B4B83C");

                    b.ToTable("TechnicalCards");
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCardIngredientComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ColdLossPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("HotLossPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("OutputWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Technica__3214EC07EF4FD960");

                    b.HasIndex("IngredientId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("TechnicalCardIngredientComposition", (string)null);
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCardSemiFinishedComposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ColdLossPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("GrossWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("HotLossPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("NetWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<decimal?>("OutputWeight")
                        .HasColumnType("decimal(10, 6)");

                    b.Property<int?>("SemiFinishedId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Technica__3214EC0776B80680");

                    b.HasIndex("SemiFinishedId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("TechnicalCardSemiFinishedComposition", (string)null);
                });

            modelBuilder.Entity("GardenNookApi.Entities.ToppingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__ToppingC__3213E83FF7AB5EB1");

                    b.ToTable("ToppingCategories");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ToppingsAndSyrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaloriesKcal")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("CarbsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<decimal?>("CostPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("CostRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("FatsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Kilojoules")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("MarkupPercent")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PriceRub")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ProteinsG")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int?>("TechnicalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Toppings__3214EC07D7C64F9B");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TechnicalCardId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("ToppingsAndSyrups");
                });

            modelBuilder.Entity("GardenNookApi.Entities.UnitsOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__UnitsOfM__3214EC0743DE010E");

                    b.ToTable("UnitsOfMeasure", (string)null);
                });

            modelBuilder.Entity("GardenNookApi.Entities.Client", b =>
                {
                    b.HasOne("GardenNookApi.Entities.ClientCategory", "ClientCategory")
                        .WithMany("Clients")
                        .HasForeignKey("ClientCategoryId")
                        .HasConstraintName("FK_Clients_ClientCategories");

                    b.Navigation("ClientCategory");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Dish", b =>
                {
                    b.HasOne("GardenNookApi.Entities.DishCategory", "Category")
                        .WithMany("Dishes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Dishes_DishCategories");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("Dishes")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_Dishes_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("Dishes")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_Dishes_UnitsOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DishTopping", b =>
                {
                    b.HasOne("GardenNookApi.Entities.OrderDishItem", "OrderDishItem")
                        .WithMany("DishToppings")
                        .HasForeignKey("OrderDishItemId")
                        .HasConstraintName("FK_DishToppings_OrderDishItems");

                    b.HasOne("GardenNookApi.Entities.ToppingsAndSyrup", "Topping")
                        .WithMany("DishToppings")
                        .HasForeignKey("ToppingId")
                        .HasConstraintName("FK_DishToppings_Toppings");

                    b.Navigation("OrderDishItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Drink", b =>
                {
                    b.HasOne("GardenNookApi.Entities.DrinkCategory", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Drinks_DrinkCategories");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("Drinks")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_Drinks_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("Drinks")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_Drinks_UnitsOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DrinkTopping", b =>
                {
                    b.HasOne("GardenNookApi.Entities.OrderDrinkItem", "OrderDrinkItem")
                        .WithMany("DrinkToppings")
                        .HasForeignKey("OrderDrinkItemId")
                        .HasConstraintName("FK_DrinkToppings_OrderDrinkItems");

                    b.HasOne("GardenNookApi.Entities.ToppingsAndSyrup", "Topping")
                        .WithMany("DrinkToppings")
                        .HasForeignKey("ToppingId")
                        .HasConstraintName("FK_DrinkToppings_Toppings");

                    b.Navigation("OrderDrinkItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Ingredient", b =>
                {
                    b.HasOne("GardenNookApi.Entities.IngredientCategory", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Ingredients_IngredientCategories");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("Ingredients")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_Ingredients_UnitsOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Inventory", b =>
                {
                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("Inventories")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_Inventory_UnitsOfMeasure");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Order", b =>
                {
                    b.HasOne("GardenNookApi.Entities.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("FK_Orders_Clients");

                    b.HasOne("GardenNookApi.Entities.Discount", "Discount")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountId")
                        .HasConstraintName("FK_Orders_Discounts");

                    b.HasOne("GardenNookApi.Entities.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("OrderTypeId")
                        .HasConstraintName("FK_Orders_OrderTypes");

                    b.HasOne("GardenNookApi.Entities.OrderStatus", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Orders_OrderStatuses");

                    b.Navigation("Client");

                    b.Navigation("Discount");

                    b.Navigation("OrderType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDishItem", b =>
                {
                    b.HasOne("GardenNookApi.Entities.Dish", "Dish")
                        .WithMany("OrderDishItems")
                        .HasForeignKey("DishId")
                        .HasConstraintName("FK_OrderDishItems_Dishes");

                    b.HasOne("GardenNookApi.Entities.Order", "Order")
                        .WithMany("OrderDishItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderDishItems_Orders");

                    b.Navigation("Dish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDrinkItem", b =>
                {
                    b.HasOne("GardenNookApi.Entities.Drink", "Drink")
                        .WithMany("OrderDrinkItems")
                        .HasForeignKey("DrinkId")
                        .HasConstraintName("FK_OrderDrinkItems_Drinks");

                    b.HasOne("GardenNookApi.Entities.Order", "Order")
                        .WithMany("OrderDrinkItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderDrinkItems_Orders");

                    b.Navigation("Drink");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderToppingItem", b =>
                {
                    b.HasOne("GardenNookApi.Entities.Order", "Order")
                        .WithMany("OrderToppingItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderToppingItems_Orders");

                    b.HasOne("GardenNookApi.Entities.ToppingsAndSyrup", "Topping")
                        .WithMany("OrderToppingItems")
                        .HasForeignKey("ToppingId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderToppingItems_Toppings");

                    b.Navigation("Order");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Preparation", b =>
                {
                    b.HasOne("GardenNookApi.Entities.SemiFinished", "SemiFinished")
                        .WithMany("Preparations")
                        .HasForeignKey("SemiFinishedId")
                        .HasConstraintName("FK_Preparations_SemiFinished");

                    b.Navigation("SemiFinished");
                });

            modelBuilder.Entity("GardenNookApi.Entities.SemiFinished", b =>
                {
                    b.HasOne("GardenNookApi.Entities.SemiFinishedCategory", "Category")
                        .WithMany("SemiFinisheds")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_SemiFinished_SemiFinishedCategories");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("SemiFinisheds")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_SemiFinished_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("SemiFinisheds")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_SemiFinished_UnitsOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Staff", b =>
                {
                    b.HasOne("GardenNookApi.Entities.StaffRole", "Role")
                        .WithMany("Staff")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Staff_StaffRoles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCardIngredientComposition", b =>
                {
                    b.HasOne("GardenNookApi.Entities.Ingredient", "Ingredient")
                        .WithMany("TechnicalCardIngredientCompositions")
                        .HasForeignKey("IngredientId")
                        .HasConstraintName("FK_TechCardIngComp_Ingredients");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("TechnicalCardIngredientCompositions")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_TechCardIngComp_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("TechnicalCardIngredientCompositions")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_TechCardIngComp_UnitsOfMeasure");

                    b.Navigation("Ingredient");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCardSemiFinishedComposition", b =>
                {
                    b.HasOne("GardenNookApi.Entities.SemiFinished", "SemiFinished")
                        .WithMany("TechnicalCardSemiFinishedCompositions")
                        .HasForeignKey("SemiFinishedId")
                        .HasConstraintName("FK_TechCardSemiComp_SemiFinished");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("TechnicalCardSemiFinishedCompositions")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_TechCardSemiComp_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("TechnicalCardSemiFinishedCompositions")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_TechCardSemiComp_UnitsOfMeasure");

                    b.Navigation("SemiFinished");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ToppingsAndSyrup", b =>
                {
                    b.HasOne("GardenNookApi.Entities.ToppingCategory", "Category")
                        .WithMany("ToppingsAndSyrups")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__ToppingsA__Categ__29221CFB");

                    b.HasOne("GardenNookApi.Entities.TechnicalCard", "TechnicalCard")
                        .WithMany("ToppingsAndSyrups")
                        .HasForeignKey("TechnicalCardId")
                        .HasConstraintName("FK_Toppings_TechnicalCards");

                    b.HasOne("GardenNookApi.Entities.UnitsOfMeasure", "UnitOfMeasure")
                        .WithMany("ToppingsAndSyrups")
                        .HasForeignKey("UnitOfMeasureId")
                        .HasConstraintName("FK_Toppings_UnitsOfMeasure");

                    b.Navigation("Category");

                    b.Navigation("TechnicalCard");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ClientCategory", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Discount", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Dish", b =>
                {
                    b.Navigation("OrderDishItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DishCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Drink", b =>
                {
                    b.Navigation("OrderDrinkItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.DrinkCategory", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Ingredient", b =>
                {
                    b.Navigation("TechnicalCardIngredientCompositions");
                });

            modelBuilder.Entity("GardenNookApi.Entities.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("GardenNookApi.Entities.Order", b =>
                {
                    b.Navigation("OrderDishItems");

                    b.Navigation("OrderDrinkItems");

                    b.Navigation("OrderToppingItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDishItem", b =>
                {
                    b.Navigation("DishToppings");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderDrinkItem", b =>
                {
                    b.Navigation("DrinkToppings");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GardenNookApi.Entities.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GardenNookApi.Entities.SemiFinished", b =>
                {
                    b.Navigation("Preparations");

                    b.Navigation("TechnicalCardSemiFinishedCompositions");
                });

            modelBuilder.Entity("GardenNookApi.Entities.SemiFinishedCategory", b =>
                {
                    b.Navigation("SemiFinisheds");
                });

            modelBuilder.Entity("GardenNookApi.Entities.StaffRole", b =>
                {
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("GardenNookApi.Entities.TechnicalCard", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Drinks");

                    b.Navigation("SemiFinisheds");

                    b.Navigation("TechnicalCardIngredientCompositions");

                    b.Navigation("TechnicalCardSemiFinishedCompositions");

                    b.Navigation("ToppingsAndSyrups");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ToppingCategory", b =>
                {
                    b.Navigation("ToppingsAndSyrups");
                });

            modelBuilder.Entity("GardenNookApi.Entities.ToppingsAndSyrup", b =>
                {
                    b.Navigation("DishToppings");

                    b.Navigation("DrinkToppings");

                    b.Navigation("OrderToppingItems");
                });

            modelBuilder.Entity("GardenNookApi.Entities.UnitsOfMeasure", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Drinks");

                    b.Navigation("Ingredients");

                    b.Navigation("Inventories");

                    b.Navigation("SemiFinisheds");

                    b.Navigation("TechnicalCardIngredientCompositions");

                    b.Navigation("TechnicalCardSemiFinishedCompositions");

                    b.Navigation("ToppingsAndSyrups");
                });
#pragma warning restore 612, 618
        }
    }
}
